"""Added a database with types

Revision ID: 4c5ccc9ce91a
Revises: 85ccbe589175
Create Date: 2023-12-18 23:48:03.113079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5ccc9ce91a'
down_revision: Union[str, None] = '85ccbe589175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('asset', sa.Column('instrument_type', sa.Integer(), nullable=False))
    op.add_column('asset', sa.Column('figi', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'asset', 'instrument_types', ['instrument_type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_column('asset', 'figi')
    op.drop_column('asset', 'instrument_type')
    op.drop_table('instrument_types')
    # ### end Alembic commands ###
