"""add Asset_ratio

Revision ID: 44f1258b7c28
Revises: 73684068545b
Create Date: 2023-12-22 17:10:27.040247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f1258b7c28'
down_revision: Union[str, None] = '73684068545b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_ratio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('figi', sa.String(length=50), nullable=True),
    sa.Column('instrument_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_type_id'], ['instrument_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_ratio')
    # ### end Alembic commands ###
