"""Add tables

Revision ID: 73684068545b
Revises: 4c5ccc9ce91a
Create Date: 2023-12-22 12:37:17.136343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73684068545b'
down_revision: Union[str, None] = '4c5ccc9ce91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('instrument_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('asset_instrument_type_fkey', 'asset', type_='foreignkey')
    op.create_foreign_key(None, 'asset', 'instrument_types', ['instrument_type_id'], ['id'])
    op.drop_column('asset', 'instrument_type')
    op.add_column('operation', sa.Column('figi', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation', 'figi')
    op.add_column('asset', sa.Column('instrument_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.create_foreign_key('asset_instrument_type_fkey', 'asset', 'instrument_types', ['instrument_type'], ['id'])
    op.drop_column('asset', 'instrument_type_id')
    # ### end Alembic commands ###
