"""empty message

Revision ID: 8f5c2da6e1d4
Revises: 44f1258b7c28
Create Date: 2023-12-23 12:45:22.813738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5c2da6e1d4'
down_revision: Union[str, None] = '44f1258b7c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'name')
    # ### end Alembic commands ###
